base_api_clashofclans:
  is_active: true
  developer_emails:
    - developer@example.com
  source_escalation: developer@example.com
  data_classification: internal
  schedules:
    - cron_schedule: "5 */4 * * *"    # every 4 hours
      execution_timezone: "UTC"
  extract_init:
    token_env_var: 'CLASHOFCLANS_API_TOKEN'
  publish_params:
    target_db: "datahelmdb"
    target_schema: "clashofclans"

CLASHOFCLANS_PLAYER_STATS:
  ingest_type: clashofclans
  description: "Ingest Clash of Clans Player Stats API into Postgres"
  developer_emails: ${base_api_clashofclans.developer_emails}
  source_escalation: ${base_api_clashofclans.source_escalation}
  data_classification: ${base_api_clashofclans.data_classification}
  schedules: ${base_api_clashofclans.schedules}
  extract_init: ${base_api_clashofclans.extract_init}
  extract_params:
    player_tag: "#CL9LJUUU"
    player_achievements: "achievements"
    player_troops: "troops"
    player_heroes: "heroes"
  publish_params: ${base_api_clashofclans.publish_params}
  target_table: "clashofclans_stats"
  columns:
    - name: "id"
      source_key: "tag"
    - name: "name"
    - name: "attackWins"
    - name: "defenseWins"
    - name: "achievements"
    - name: "troops"
    - name: "heroes"
    - name: "last_mtime"
